---
title: "Untitled"
author: "Stacey Butler"
date: "6/6/2017"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
# install.packages("combinat")
# install.packages("maptree")
# install.packages("e1071")
# 
# library(combinat)
# library(maptree)
# library(e1071)

```
```{r, message=FALSE}
if (!require('vcfR')) install.packages('vcfR') 
library('vcfR')
```

### get data ###
```{r}
### get genomic data from terraref ###

vcf_data <- read.vcfR(file="/data/terraref/sites/genomics/derived_data/ril/gbs/imp_TERRA_RIL_SNP.vcf")

### @gt contains the genomic data ###

vcf_gt = vcf_data@gt

### columns 286:304 were determined to match traits data from genesys ###

vcf_gt_match <- vcf_gt[,286:304]

View(vcf_gt_match)
```
### mary a's original distance code ###
```{r}

names <-c('0|0','0|1','1|0','1|1')
allele_dif_table <- matrix(c(0,1,1,2,1,0,0,1,1,0,0,1,2,1,1,0),
                           nrow = 4,ncol = 4, dimnames = list(names, names))
#cityblock distance: to get a cityblock magnitude, set a2 to '0|0'.  This is similar to the l_1 distance of a vector
cityblock<- function(a1,a2){
  
  vec1<-a1[]
  vec2<-a2[]
  vec1[a1=='0|0']<-0
  vec2[a2=='0|0']<-0
  vec1[a1=='1|1']<-2
  vec2[a2=='1|1']<-2
  vec1[a1=='0|1' | a1 == '1|0']<-1
  vec2[a2=='0|1' | a2 == '1|0']<-1
  
 dif<- sum(abs(as.numeric(vec2)-as.numeric(vec1)))
}

```

### updated distance functions ###
```{r}
# distance 1
hamming <- function(x,y) {
  if(length(x)!=length(y)){
    print('error, vectors not same size!')
  }else{
    result <- length(x[x!=y])
    
    return(result)
  }
}

#turns genomes into vectors with entries 0,1,2, where '0|0'-> 0; '0|1','1|0' ->1; '1|1'-> 2. 

tonumericform <- function(a){
  vec1<-matrix(nrow = length(a),ncol =2)
  vec1[a=='0|0']<-c(0,0)
  vec1[a=='1|1']<-c(1,1)
  vec1[a=='0|1']<-c(0,1)
  vec1[a == '1|0']<-c(1,0)
  return(as.numeric(vec1)) 
} 

#cityblock distance: to get a cityblock magnitude, set a2 to '0|0'.  This is similar to the l_1 distance of a vector

# distance 2
cityblock<- function(a1,a2){

  vec1<-tonumericform(a1)
  vec2<-tonumericform(a2)
  point_dif<-vec1-vec2
  dif<- sum(abs(vec1-vec2))
  return(dif)
}

#Euclidean distance: to get a Euclidean Magnitude, set a2 to '0|0''

euclidean<- function(a1,a2){
  vec1<-tonumericform(a1)
  vec2<-tonumericform(a2)
  dif <- norm(vec1-vec2,"2")
}


```
```{r}

#num_gen <- ncol(vcf_gt_data)
# d_matrix <- matrix(nrow=19,ncol=19)
# for(i in 1:19){
#   d_matrix[i,i] <- 0
#   for(j in 1:i-1){
#     d_matrix[i,j] <- d_matrix[j,i] <- cityblock(vcf_gt_match[,i],vcf_gt_match[,j])
#   }
# }


```


### produce matrix of pairwise distances between genomes ###
```{r}

dist_matrix <- function(vcf_gt_data,FUN=cityblock){
  num_gen <- ncol(vcf_gt_data)
  d_m     <- matrix(nrow=num_gen,ncol=num_gen)
  for(i in 1:num_gen){
    d_m[i,i] <- 0
    for(j in 1:i-1){
      d_m[i,j] <- d_m[j,i] <- FUN(vcf_gt_data[,i],vcf_gt_data[,j])
    }
  }
  return(d_m)
}
```
```{r}
#d_matrix1 <- dist_matrix(vcf_gt_match, FUN=hamming)
#View(d_matrix)
d_matrix2 <- dist_matrix(vcf_gt[,200:304], FUN=cityblock)
#View(d_matrix2)
#d_matrix3 <- dist_matrix(vcf_gt_match, FUN=euclidean)
#View(d_matrix3)


```

### Cluster Dendrogram ###

```{r}


cl_tree1 <- hclust(as.dist(d_matrix1))

plot(cl_tree1,main='Cluster Dendrogram for Matching Cultivars, D1')
```
```{r}
cl_tree2 <- hclust(as.dist(d_matrix2))

plot(cl_tree2,main='Cluster Dendrogram for Matching Cultivars, D2')
```
```{r}
if(!require(dendextend)) install.packages("dendextend")
library("dendextend")
```

```{r}
dend <- as.dendrogram(cl_tree2)
dend <- color_branches(dend, k=3)

#library(colorspace)
plot(dend,main='Cluster Dendrogram for All Cultivars, D2')
```
```{r}
#Save picture:
png(file="cluster_dend_all.png",width=1800,height = 400)
plot(dend,main='Cluster Dendrogram for All Cultivars, D2')
dev.off()
```

```{r}
if(!require(circlize)) install.packages('circlize')
library(circlize)
circlize_dendrogram(dend)

```
#####################
```{r}
png("plot.png",width=1800,height=400)
plot(cl_tree,main='Cluster Dendrogram for Matching Cultivars')
dev.off()
```

```{r}

heatmap(d_matrix,sym=TRUE)


```
```{r}

heatmap(d_matrix,Rowv = as.dendrogram(cl_tree2),sym=TRUE)


```

## Extracting genesys data 
```{r, message=F, warning=F}
library(dplyr)
accessions <- read.csv("~/Team5/data/df_traits_nutrition.csv")

genesys_nutrition <- accessions %>%
  mutate(acceNumb = gsub("PI ", "PI", acceNumb))

accessions <- read.csv("~/Team5/data/df_traits_growth.csv")

genesys_growth <- accessions %>%
  mutate(acceNumb = gsub("PI ", "PI", acceNumb))

```

```{r}
#genesys_nut_sort <- genesys_nutrition[order(genesys_nutrition$acceNumb),]
#genesys_growth_sort <- genesys_growth[order(genesys_growth$acceNumb),]
#genesys_growth$acceNumb
#genesys_nutrition$acceNumb
match_2_genesys<-genesys_growth$acceNumb %in% genesys_nutrition$acceNumb

genesys_growth2 <- genesys_growth[match_2_genesys]

match_2_genesys<-genesys_nutrition$acceNumb %in% genesys_growth$acceNumb

genesys_nutrition2 <- genesys_nutrition[match_2_genesys]

genesys_total <-

```
```{r}


```


